version: '3'

services:
  chat-app-1:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CORS_ORIGIN=${CORS_ORIGIN}
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}